<?php

//Project Euler #2: Even Fibonacci numbers
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

$first_num = 0;
$second_num = 1;
    
do{
    
    $add = $first_num + $second_num;
    
    if($add % 2 == 0){

        $sum_even += $add;

    }
    
    $temp = $second_num + $first_num;
    $first_num = $second_num;
    $second_num = $temp;
    
}
while($second_num<4000000);

echo $sum_even;


?>